#+TITLE: The Draft of ANSI Common Lisp Standard

* About

This package installs the publiclly available draft of Common Lisp standard in Info format into Emacs.
The converted info files of the draft as originally found in [[https://github.com/jwiegley/ready-lisp][Ready Lisp by J. Wiegley]].

* Install

Clone this repo to your computer. Open the directory in Emacs, and than M-x package-install-file.

* Usage

Once installed, open the Info, C-h i. There should be a new Menu node, Common Lisp, and an entry for the draft under the menu.

* Remark

I have seen various versions of the draft online as web versions, as well as verious Info versions. I prefer the one found here, and find it handy to read it from Emacs. I hope I am not infring in anyone's IP. If I do, than let me know and I'll take it down. I have turn this into an easy to install Emacs package for the mere convenience and the joy for using the Common Lisp language.

In the private conversion the editor of the Draft, K. Pitman, wrote about copyrights:

"This is generally believed to be in the public domain, though there is no way to assure that. An explanation of that is in my article [[https://nhplace.com/kent/Papers/cl-untold-story.html][Common Lisp: The Untold Story]], which was published in the 50th Anniversary of Lisp conference."


